title: SeedLang
email: codingpotato@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  SeedLang is an embeddable and visualizable scripting engine for .Net and
  Unity. Here is the documentation site of SeedLang.
baseurl: "/SeedLang"
url: "https://seedv.github.io"
twitter_username: jekyllrb
github_username: SeedV

aux_links:
  "SeedLang on GitHub":
    - "https://github.com/SeedV/SeedLang"

remote_theme: just-the-docs/just-the-docs
# theme: just-the-docs
plugins:
  - jekyll-feed
