name: Coverage

on:
  push:
    branches: [wip_codingpotato_codecov]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        working-directory: ./csharp
        run: dotnet restore
      - name: Build
        working-directory: ./csharp
        run: dotnet build --no-restore
      - name: Run unit tests
        working-directory: ./csharp
        run: |
          dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ \
          /p:CoverletOutputFormat=opencover /p:ExcludeByFile="**/obj/**/*.cs"
      - name: Codecov
        uses: codecov/codecov-action@v1
